# What is PyTorch?

It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

## Getting Started

### Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.3674e-39, 1.0929e-38, 1.0469e-38],
        [1.0561e-38, 6.2449e-39, 1.0837e-38],
        [1.0102e-38, 1.0561e-38, 5.9694e-39],
        [8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3772, 0.3300, 0.1223],
        [0.9410, 0.3381, 0.7372],
        [0.6261, 0.1878, 0.9666],
        [0.8897, 0.8055, 0.0750],
        [0.1536, 0.3220, 0.8074]])


  Construct a matrix filled zeros and of dtype `int64`:

In [4]:
x = torch.zeros(5, 3, dtype=torch.int64)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.1401,  0.3113, -1.0106],
        [-1.2562, -0.0772,  1.6537],
        [-1.1801, -0.4725,  0.2219],
        [-0.6175,  2.0769, -0.1218],
        [-0.4604, -0.5398,  0.6999]])


Get its size:

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### note
     torch.Size is in fact a tuple, so it supports all tuple operations.

### Operations

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.0233e+00,  4.3399e-01, -1.6020e-01],
        [-8.8418e-01,  7.8293e-01,  2.4271e+00],
        [-5.0434e-01, -1.0913e-01,  5.3728e-01],
        [-4.3413e-02,  2.2710e+00,  2.8562e-01],
        [ 3.4634e-01,  1.1158e-03,  1.3862e+00]])


Addition: syntax 2

In [9]:
print(torch.add(x, y))

tensor([[-1.0233e+00,  4.3399e-01, -1.6020e-01],
        [-8.8418e-01,  7.8293e-01,  2.4271e+00],
        [-5.0434e-01, -1.0913e-01,  5.3728e-01],
        [-4.3413e-02,  2.2710e+00,  2.8562e-01],
        [ 3.4634e-01,  1.1158e-03,  1.3862e+00]])


Addition: providing an output tensor as argument

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

def x():
    print()

tensor([[-1.0233e+00,  4.3399e-01, -1.6020e-01],
        [-8.8418e-01,  7.8293e-01,  2.4271e+00],
        [-5.0434e-01, -1.0913e-01,  5.3728e-01],
        [-4.3413e-02,  2.2710e+00,  2.8562e-01],
        [ 3.4634e-01,  1.1158e-03,  1.3862e+00]])


Addition: in-place

In [11]:
# adds x to y
y.add_(x)
print(y)

# or
y += x
print(y)

tensor([[-1.0233e+00,  4.3399e-01, -1.6020e-01],
        [-8.8418e-01,  7.8293e-01,  2.4271e+00],
        [-5.0434e-01, -1.0913e-01,  5.3728e-01],
        [-4.3413e-02,  2.2710e+00,  2.8562e-01],
        [ 3.4634e-01,  1.1158e-03,  1.3862e+00]])
tensor([[-2.1634,  0.7453, -1.1708],
        [-2.1404,  0.7057,  4.0807],
        [-1.6845, -0.5817,  0.7592],
        [-0.6609,  4.3479,  0.1638],
        [-0.1141, -0.5387,  2.0861]])


#### note
    Any operation that mutates a tensor in-place is post-fixed with an _.
    For example: x.copy_(y), x.t_(), will change x.

You can use standard NumPy-like indexing with all bells and whistles!

In [12]:
print(x[:, 1])

tensor([ 0.3113, -0.0772, -0.4725,  2.0769, -0.5398])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.3271])
1.3270564079284668


**Read later:**


100+ Tensor operations, including transposing, indexing, slicing,
mathematical operations, linear algebra, random numbers, etc.,
are described
[here](http://pytorch.org/docs/torch).

## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch `Tensor` and NumPy `array` will share their underlying memory
locations, and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [17]:
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

## CUDA Tensors

Tensors can be moved onto any device using the ``.to`` method.

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!